### ISSUE TITLE
Kafka sink raises error when `key_path` is specified in the config

### ISSUE THREAD

**Issue by StewartJingga** [odpf/meteor#216] opened 2021-09-16 02:59 UTC
**Describe the bug**
Kafka sink fails to add key to its message due to changes in Metadata models. (Urn is now nested inside Resource)

**To Reproduce**
1. Create a recipe with kafka sink
2. Set `key_path` value 
3. Run recipe

**Expected behavior**
The recipe should be working properly with `key_path` and key should be published

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. 10.15]

**Comment by sudo-suhas** [comment] 2023-01-03 07:29
Is this issue still present? I ran the following recipe and it was able to sink it successfully to Kafka:

Recipe **application_yaml.yaml**:

```yaml
name: application_yaml-test
version: v1beta1
source:
  name: application_yaml
  scope: application-test
  config:
    file: plugins/extractors/application_yaml/testdata/application.detailed.yaml
sinks:
  - name: kafka
    config:
      brokers: "127.0.0.1:59594"
      topic: meteor-application-sink
      key_path: .Urn
```

Simulate Kafka locally using Redpanda:

```
$ brew install redpanda-data/tap/redpanda
...
$ rpk container start -n 1
Downloading latest version of Redpanda
Starting cluster
Waiting for the cluster to be ready...
  NODE ID  ADDRESS
  0        127.0.0.1:59594

Cluster started! You may use rpk to interact with it. E.g:

  rpk cluster info --brokers 127.0.0.1:59594

You may also set an environment variable with the comma-separated list of broker addresses:

  export REDPANDA_BROKERS="127.0.0.1:59594"
  rpk cluster info

$ rpk topic create meteor-application-sink --brokers=127.0.0.1:59594
TOPIC                    STATUS
meteor-application-sink  OK
```

Recipe run:

```
$ meteor run ./_recipes/application_yaml.yaml
INFO[0000] running recipe                                recipe=application_yaml-test
INFO[0000] Successfully extracted record                 recipe=application_yaml-test record="urn:application_yaml:application-test:application:test"
INFO[0001] Successfully published record                 recipe=application_yaml-test sink=kafka
INFO[0001] done running recipe                           duration_ms=1040 recipe=application_yaml-test record_count=1
running recipes  100% |████████████████████████████████████████| (1/1)
All recipes ran successful
0 failing, 1 successful, and 1 total

Status	Recipe               	Source          	Duration(ms)	Records
✓     	application_yaml-test	application_yaml	0 ms        	1
INFO[0001] force closing run                             recipe=application_yaml-test
```

Produced message:
```
$ rpk topic consume meteor-application-sink --num 1 --brokers=127.0.0.1:59594
{
  "topic": "meteor-application-sink",
  "key": "\n6urn:application_yaml:application-test:application:test",
  "value": "\n6urn:application_yaml:application-test:application:test\u0012\u0004test\u001a\u0010application_yaml\"\u000bapplication*\u001ehttp://company.com/myteam/test2\u0015My incredible project:[\n3type.googleapis.com/odpf.assets.v1beta2.Application\u0012$\n\u0007test-id\u0012\u0007c23sdf6\ufffd\u0006\u0006\u0008\ufffd\ufffd\ufffd\ufffd\u0004\ufffd\u0006\u0006\u0008\ufffd\ufffd\ufffd\ufffd\u0004\ufffd\u0001!\n\u0003123\u0012\u0006myteam\"\u0012myteam@company.com\ufffd\u0002\ufffd\u0002\ne\ncurn:bigquery:bq-raw-internal:table:bq-raw-internal:dagstream.production_feast09_s2id13_30min_demand\nS\nQurn:kafka:int-dagstream-kafka.yonkou.io:topic:staging_feast09_s2id13_30min_demand\u0012u\nsurn:kafka:1-my-kafka.company.com,2-my-kafka.company.com:topic:staging_feast09_mixed_granularity_demand_forecast_3es\ufffd\u0002\u0006\n\u0001x\u0012\u0001y",
  "timestamp": 1672725884827,
  "partition": 0,
  "offset": 0
}
```

**Comment by sudo-suhas** [comment] 2023-01-10 04:48
Closing as the issue is not reproducible.

**Closed by sudo-suhas** 2023-01-10 04:48 UTC
Labels: bug, sink
